
INSERT INTO users_data(ID, CURRENT_LEVEL, EMAIL, NAME, PASSWORD)
VALUES(10001, 1, 'DFENNELL31@GMAIL.COM', 'David', 'test');

INSERT INTO users_data(ID, CURRENT_LEVEL, EMAIL, NAME, PASSWORD)
VALUES(10002, 1, 'DFENNELL31@GMAIL.COM', 'David', 'test');

INSERT INTO users_data(ID, CURRENT_LEVEL, EMAIL, NAME, PASSWORD)
VALUES(10003, 1, 'DFENNELL31@GMAIL.COM', 'David', 'test');

